"""Create auto trader table

Revision ID: 0a41894a2fa4
Revises: 643f469b8829
Create Date: 2026-01-04 13:51:11.153803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a41894a2fa4"
down_revision: str | Sequence[str] | None = "643f469b8829"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auto_trader_crypto_currency",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("activated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auto_trader_crypto_currency")
    # ### end Alembic commands ###
