"""Add open_trades_on_weekends column to risk_management

Revision ID: 139e5353d6dd
Revises: ad10cee819e2
Create Date: 2026-04-21 10:12:37.560751

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "139e5353d6dd"
down_revision: str | Sequence[str] | None = "ad10cee819e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "risk_management", sa.Column("open_trades_on_weekends", sa.Boolean(), nullable=False, server_default="1")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_management", "open_trades_on_weekends")
    # ### end Alembic commands ###
