"""Create entire database

Revision ID: 46e9c21728b2
Revises:
Create Date: 2025-12-19 08:41:38.592157

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46e9c21728b2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_signal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("crypto_currency", sa.String(), nullable=False),
        sa.Column("timeframe", sa.String(), nullable=False),
        sa.Column("position_type", sa.Enum("LONG", "SHORT", name="positiontypeenum"), nullable=False),
        sa.Column("action_type", sa.Enum("ENTRY", "EXIT", name="marketactiontypeenum"), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=True),
        sa.Column("break_even_price", sa.Float(), nullable=True),
        sa.Column("stop_loss_percent_value", sa.Float(), nullable=True),
        sa.Column("take_profit_percent_value", sa.Float(), nullable=True),
        sa.Column("stop_loss_price", sa.Float(), nullable=True),
        sa.Column("take_profit_price", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "push_notification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_type", sa.Enum("SIGNALS", "FATAL_ERRORS", name="pushnotificationtypeenum"), nullable=False
        ),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("activated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notification_type", "chat_id"),
    )
    op.create_table(
        "signal_parametrization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("crypto_currency", sa.String(), nullable=False),
        sa.Column("atr_sl_mult", sa.Float(), nullable=False),
        sa.Column("atr_tp_mult", sa.Float(), nullable=False),
        sa.Column("long_entry_oversold_threshold", sa.Float(), nullable=False),
        sa.Column("short_entry_overbought_threshold", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crypto_currency", name="uq_signal_parametrization"),
    )
    op.create_table(
        "tracked_crypto_currency",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tracked_crypto_currency")
    op.drop_table("signal_parametrization")
    op.drop_table("push_notification")
    op.drop_table("market_signal")
    # ### end Alembic commands ###
