"""Add number concurrent trades column

Revision ID: ad10cee819e2
Revises: b43661c2abd1
Create Date: 2026-01-17 18:10:19.429270

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad10cee819e2"
down_revision: str | Sequence[str] | None = "b43661c2abd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("risk_management", sa.Column("number_of_concurrent_trades", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_management", "number_of_concurrent_trades")
    # ### end Alembic commands ###
