"""Add double confirm trend column

Revision ID: b43661c2abd1
Revises: 0a41894a2fa4
Create Date: 2026-01-11 21:42:08.909204

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b43661c2abd1"
down_revision: str | Sequence[str] | None = "0a41894a2fa4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signal_parametrization", sa.Column("double_confirm_trend", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("signal_parametrization", "double_confirm_trend")
    # ### end Alembic commands ###
