"""Create signal parametrization table

Revision ID: c1097edd00fa
Revises: 83a8218baec9
Create Date: 2025-12-15 12:57:57.981683

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1097edd00fa"
down_revision: str | Sequence[str] | None = "83a8218baec9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signal_parametrization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("crypto_currency", sa.String(), nullable=False),
        sa.Column("atr_sl_mult", sa.Float(), nullable=False),
        sa.Column("atr_tp_mult", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crypto_currency", name="uq_signal_parametrization"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signal_parametrization")
    # ### end Alembic commands ###
