"""Create market signal table

Revision ID: cb1c81168294
Revises: e3bc8dac596f
Create Date: 2025-12-13 11:40:21.718594

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb1c81168294"
down_revision: str | Sequence[str] | None = "e3bc8dac596f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_signal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("crypto_currency", sa.String(), nullable=False),
        sa.Column("timeframe", sa.String(), nullable=False),
        sa.Column(
            "signal_type",
            sa.Enum("LONG_ENTRY", "LONG_EXIT", "SHORT_ENTRY", "SHORT_EXIT", name="marketsignaltypeenum"),
            nullable=False,
        ),
        sa.Column("entry_price", sa.Float(), nullable=True),
        sa.Column("break_event_price", sa.Float(), nullable=True),
        sa.Column("sl_percent", sa.Float(), nullable=True),
        sa.Column("tp_percent", sa.Float(), nullable=True),
        sa.Column("sl_price", sa.Float(), nullable=True),
        sa.Column("tp_price", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("market_signal")
    # ### end Alembic commands ###
