"""Create risk management table

Revision ID: cbe21a14a3b0
Revises: 46e9c21728b2
Create Date: 2025-12-28 18:16:37.636560

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbe21a14a3b0"
down_revision: str | Sequence[str] | None = "46e9c21728b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_management",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("percent_value", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_management")
    # ### end Alembic commands ###
