"""Create push notification table

Revision ID: e3bc8dac596f
Revises: 7f910168fa04
Create Date: 2025-12-10 19:24:54.924990

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3bc8dac596f"
down_revision: str | Sequence[str] | None = "7f910168fa04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_notification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.Enum("SIGNALS", name="pushnotificationtypeenum"), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("activated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("notification_type", "chat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("push_notification")
    # ### end Alembic commands ###
