import numpy as np

TELEGRAM_REPLY_EXCEPTION_MESSAGE_MAX_LENGTH = 3_000
DEFAULT_CURRENCY_CODE = "USDT"
STABLE_COINS = [DEFAULT_CURRENCY_CODE, "USDC"]
DEFAULT_JOB_INTERVAL_SECONDS = 5  # 5 seconds
DEFAULT_IN_MEMORY_CACHE_TTL_IN_SECONDS = 86_400  # 1 day
SIGNALS_TASK_SERVICE_CRON_PATTERN = [0, 1, 2, 5, 15, 16, 17, 18, 30, 31, 32, 33, 35, 45, 46, 47, 48, 55]
DEFAULT_STOCH_RSI_OVERSOLD_AREA = 0.20
DEFAULT_STOCH_RSI_OVERBOUGHT_AREA = 0.80
DEFAULT_ATR_SL_MULT = 2.8
DEFAULT_ATR_TP_MULT = 3.5
# Event Emitter - Event names
SIGNALS_EVALUATION_RESULT_EVENT_NAME = "signals_evaluation_result"
TRIGGER_BUY_ACTION_EVENT_NAME = "trigger_buy_action"

RISK_MANAGEMENT_ALLOWED_VALUES_LIST = STOP_LOSS_STEPS_VALUE_LIST = np.concatenate(
    (np.arange(0.25, 5.25, 0.25), np.arange(5.50, 10.50, 0.50), np.arange(11, 21, 1))
).tolist()

MEXC_FUTURES_TAKER_FEES = 0.0004
